# Generated by Django 4.1.7 on 2024-02-12 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('natio', models.CharField(max_length=12)),
                ('medsos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('book_type', models.CharField(choices=[('SERIES', 'Series'), ('ONE-SHOT', 'One-shot')], max_length=10, null=True)),
                ('tl_type', models.CharField(choices=[('FAN TRANSLATION', 'FAN TRANSLATION'), ('OFFICIAL TRANSLATION', 'OFFICIAL TRANSLATION'), ('FAN + OFFICIAL', 'FAN + OFFICIAL')], max_length=20, null=True)),
                ('source', models.CharField(max_length=100)),
                ('reading_status', models.CharField(choices=[('DROP', 'DROP'), ('ON-HOLD', 'ON-HOLD'), ('FINISH', 'FINISH'), ('NOT YET READ', 'NOT YET READ'), ('TO READ', 'TO RAED')], max_length=20)),
                ('current_progress', models.CharField(max_length=30, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.author')),
            ],
        ),
    ]
