# Generated by Django 4.1.7 on 2024-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.CharField(max_length=110, null=True),
        ),
    ]
