# Generated by Django 4.1.7 on 2024-02-17 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40)),
                ('auhor_nationality', models.CharField(max_length=20)),
                ('author_medsos', models.CharField(max_length=30)),
                ('books', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='auhor_nationality',
            field=models.CharField(default='Japanese', max_length=20),
        ),
        migrations.AddField(
            model_name='books',
            name='author_medsos',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='books',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='books',
            name='series_status',
            field=models.CharField(choices=[('FINISH', 'FINISH'), ('ON-GOING', 'ON-GOING')], default='ON-GOING', max_length=20),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='books',
            name='reading_status',
            field=models.CharField(choices=[('DROP', 'DROP'), ('ON-HOLD', 'ON-HOLD'), ('FINISH', 'FINISH'), ('NOT YET READ', 'NOT YET READ'), ('TO READ', 'TO RAED')], default='TO READ', max_length=20),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
