# Generated by Django 4.1.7 on 2024-02-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='series_status',
            field=models.CharField(choices=[('FINISH', 'FINISH'), ('ON-GOING', 'ON-GOING')], default='ON-GOING', max_length=20),
        ),
        migrations.AlterField(
            model_name='books',
            name='reading_status',
            field=models.CharField(choices=[('DROP', 'DROP'), ('ON-HOLD', 'ON-HOLD'), ('FINISH', 'FINISH'), ('NOT YET READ', 'NOT YET READ'), ('TO READ', 'TO RAED')], default='TO READ', max_length=20),
        ),
    ]
