# Generated by Django 4.1.7 on 2024-03-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_series_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='pub_en',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='pub_jp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
