# Generated by Django 4.1.7 on 2024-03-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_series_pub_en_alter_series_pub_jp'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='desc',
            field=models.TextField(default='-', max_length=300),
        ),
    ]
