# Generated by Django 4.1.7 on 2024-02-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_auhor_nationality_books_author_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.FileField(default='cover/default.png', upload_to='cover/'),
        ),
    ]
