# Generated by Django 4.1.7 on 2024-02-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='auhor_nationality',
            new_name='author_nationality',
        ),
    ]
