# Generated by Django 4.1.7 on 2024-02-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_auhor_nationality_archive_author_nationality'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Notes',
        ),
    ]
