# Generated by Django 4.1.7 on 2024-02-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_review_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='review',
            new_name='note',
        ),
    ]
