# Generated by Django 4.1.7 on 2024-02-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blacklist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
