# Generated by Django 4.1.7 on 2024-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
