# Generated by Django 4.1.7 on 2024-03-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_archive_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='book_type',
            field=models.CharField(choices=[('SERIES', 'Series'), ('ONE-SHOT', 'One-shot')], max_length=10, null=True),
        ),
    ]
