# Generated by Django 4.1.7 on 2024-03-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_archive_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='books',
            field=models.CharField(max_length=100),
        ),
    ]
