# Generated by Django 4.1.7 on 2024-03-02 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_archive_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='books',
            new_name='title',
        ),
    ]
