# Generated by Django 4.1.7 on 2024-03-02 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_books_archive_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('author_medsos', models.CharField(blank=True, default='none', max_length=30)),
                ('book_type', models.CharField(choices=[('SERIES', 'Series'), ('ONE-SHOT', 'One-shot')], max_length=10, null=True)),
                ('tl_type', models.CharField(choices=[('FAN TRANSLATION', 'FAN TRANSLATION'), ('OFFICIAL TRANSLATION', 'OFFICIAL TRANSLATION'), ('FAN + OFFICIAL', 'FAN + OFFICIAL')], max_length=20, null=True)),
                ('series_status', models.CharField(choices=[('FINISH', 'FINISH'), ('ON-GOING', 'ON-GOING')], default='ON-GOING', max_length=20)),
                ('source', models.CharField(blank=True, default='none', max_length=100)),
                ('reading_status', models.CharField(choices=[('DROP', 'DROP'), ('ON-HOLD', 'ON-HOLD'), ('FINISH', 'FINISH'), ('NOT YET READ', 'NOT YET READ'), ('TO READ', 'TO READ'), ('READING', 'READING')], default='TO READ', max_length=20)),
                ('current_progress', models.CharField(blank=True, default='not yet read', max_length=30)),
                ('cover', models.FileField(blank=True, default='cover/default.png', upload_to='cover/')),
                ('genre', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.ManyToManyField(to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(null=True)),
                ('note', models.TextField()),
                ('books', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.library')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='books',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
