# Generated by Django 4.1.7 on 2024-03-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_user_library_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='source',
        ),
        migrations.AddField(
            model_name='note',
            name='source',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='library',
            name='profile',
            field=models.ManyToManyField(null=True, to='core.profile'),
        ),
    ]
