# Generated by Django 4.1.7 on 2024-03-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_library_source_note_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='profile',
            field=models.ManyToManyField(to='core.profile'),
        ),
        migrations.AlterField(
            model_name='library',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
