# Generated by Django 4.1.7 on 2024-03-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_library_author_alter_library_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
