# Generated by Django 4.1.7 on 2024-03-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_library_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='books',
            new_name='book',
        ),
    ]
