# Generated by Django 4.1.7 on 2024-03-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_books_note_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
