# Generated by Django 4.1.7 on 2024-03-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_note_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
