# Generated by Django 4.1.7 on 2024-03-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_library_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
