# Generated by Django 4.1.7 on 2024-03-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_library_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
