# BOOKS TYPES
SER = "SERIES"
ONS = "ONE-SHOT"

# TRANSLATION BY
FAN = "FAN TRANSLATION"
OFF = "OFFICIAL TRANSLATION" 
BOT = "FAN + OFFICIAL"

# READING STATUS
DRO = "DROP"
ONH = "ON-HOLD"
FIN = "FINISH"
NOR = "NOT YET READ"
TOR = "TO READ"
REA = "READING"

#SERIES_STATUS 
FINE = "FINISH"
ONG = "ON-GOING"

BOOKS_TYPES = (
    (SER, "Series"),
    (ONS,  "One-shot")
)

TRANSLATION_BY = (
    (FAN, "FAN TRANSLATION"),
    (OFF, "OFFICIAL TRANSLATION"),
    (BOT, "FAN + OFFICIAL")
)
SERIES_STATUS = (
    (FINE, "FINISH"),
    (ONG, "ON-GOING")
)
READING_STATUS = (
    (DRO, "DROP"),
    (ONH, "ON-HOLD"),
    (FIN, "FINISH"),
    (NOR, "NOT YET READ"),
    (TOR, "TO READ"),
    (REA, "READING")
)