# BOOKS TYPES
SER = "SERIES"
ONS = "ONE-SHOT"

# TRANSLATION STATUS
FAN = "FAN TRANSLATION"
OFF = "OFFICIAL TRANSLATION" 
BOT = "FAN + OFFICIAL"

# READING STATUS
DRO = "DROP"
ONH = "ON-HOLD"
FIN = "FINISH"
NOR = "NOT YET READ"
TOR = "TO READ"

BOOKS_TYPES = (
    (SER, "Series"),
    (ONS,  "One-shot")
)

TRANSLATION_STATUS = (
    (FAN, "FAN TRANSLATION"),
    (OFF, "OFFICIAL TRANSLATION"),
    (BOT, "FAN + OFFICIAL")
)
READING_STATUS = (
    (DRO, "DROP"),
    (ONH, "ON-HOLD"),
    (FIN, "FINISH"),
    (NOR, "NOT YET READ"),
    (TOR, "TO RAED")
)